apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-container 
          image: 69966/reactjsimage:latest
          ports:
            - containerPort: 80
      #     volumeMounts:
      #       - name: my-vol
      #         mountPath: /app/src/main/resources/images
      # volumes:
      #   - name: my-vol 
      #     nfs:
      #       server: 10.148.0.12
      #       path: /opt/nfs/data
---
apiVersion: v1
kind: Service 
metadata:
  name: spring-svc
spec:
  type: ClusterIP
  selector:
    app: spring-app
  ports:
    - port: 80
      targetPort: 80
---
# create ingress for the spring application 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingresClassName: nginx
spec:
  tls:
    - hosts:
        - spring.visal.me
      secretName: myspring-tls 
  rules:
    - host: spring.visal.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-svc
                port:
                  number: 80